name: GitHub Actions Demo

on:
  push: 
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_requests:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  my-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This job was triggered by event: ${{ github.event_name }} :rocket:"
          echo "The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: |
          
          
